---
pivnet-api-token: dbe9ce017e1145d589034710a42548f1-r
pivnet-file-glob: pivotal-container-service-*.pivotal
pivnet-product-slug: pivotal-container-service
product-version-regex: 1\.3\.(.*)
stemcell-iaas: google
